<Project>

    <PropertyGroup>
        <Version>7.24.5</Version>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <Nullable>annotations</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Authors>Miaomiao contributors; 2dust and v2rayN contributors</Authors>
        <Company>Miaomiao</Company>
        <Product>Miaomiao</Product>
        <RepositoryUrl>https://github.com/rmomo5285-droid/Miaomiao-Desktop</RepositoryUrl>
        <Description>Miaomiao cross-platform network client</Description>
        <PackageLicenseExpression>GPL-3.0</PackageLicenseExpression>
        <Copyright>Copyright © 2017-$([System.DateTime]::UtcNow.Year) Miaomiao and v2rayN contributors</Copyright>
        <InvariantGlobalization>false</InvariantGlobalization>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>embedded</DebugType>
        <EventSourceSupport>false</EventSourceSupport>
        <StackTraceSupport>false</StackTraceSupport>
        <MetricsSupport>false</MetricsSupport>
        <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
        <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
        <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>

        <UseSystemResourceKeys>true</UseSystemResourceKeys>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishReadyToRun>false</PublishReadyToRun>
    </PropertyGroup>
</Project>
